### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#158]
EventFlow needs to support .NET Core. Maybe start with the `EventFlow` and `EventFlow.Autofac` packages.

To do
- [x] convert EventFlow to new VS2017 project format (#303)
- [ ] add `netstandard1.x` NuGet packages along side `net451`

**Comment by rasmus** [comment]
Autofac also has .NET Core support https://github.com/autofac/Autofac

**Comment by rasmus** [comment]
http://www.michael-whelan.net/porting-dotnet-framework-library-to-dotnet-core/

**Comment by rasmus** [comment]
Don't go for project.json given this article https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/

**Comment by rasmus** [comment]
https://github.com/louthy/csharp-monad/commit/7aea9a3769dad107d705a38609ff1e3caf905389

**Comment by ArieJones** [comment]
I am wondering how this is coming along since .NET core has stabilized quite a bit?

The project.json piece is not an issue as it should be automatically converted once they switch over to csproj.

**Comment by rasmus** [comment]
@ArieJones I haven't had the time to really get started on .NET core yet 😢

**Comment by rasmus** [comment]
Working on this using the new csproj format in #291

**Comment by rasmus** [comment]
https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/

**Comment by xorcrud** [comment]
just wanted to let you know that:
a) the eventflow architecture seems consice/elegant and the code consistent and pretty much optimized
b) .net core would be much appreciated. But seems non trivial (a lot of work, not especially difficult)

The consideration of using EventFlow is the only thing which holds me back from using .net core at the moment. Looking into porting EventFlow to .net core myself (which is why i have been reading your code in the first place).

**Comment by rasmus** [comment]
@xorcrud I'm working on upgrading the project to the new csproj format in PR #291 which will simplify the task of supporting .NET Core greatly. However, the new format is still in preview and there's some issues regarding integration with Paket. As soon as both Paket and the new csproj format stabilizes I'll continue on the update.

**Comment by petersondrew** [comment]
So I'm trying to follow the PRs involved here, it looks like this is still blocked by converting to the new project format because #303 was reverted by #312 right?

**Comment by rasmus** [comment]
@petersondrew its implemented, #303 was the start then I implemnted .NET standard in #330. The new project format was the first step.

**Comment by rasmus** [comment]
@xorcrud .net standard (and thereby .net core support) is done

**Comment by mattgi** [comment]
@rasmus is it possible to provide some guidance in the documentation on how to set up a multi-project solution based on CORE 2.0 Web API, some Domain Services, and I guess RabbitMQ, ElasticSearch (or SQL), and EventStore.org? Keen to know how to wire it all from an IoC perspective using the built-in support provided by MSoft in Web API projects.

**Comment by ppumkin** [comment]
@mattgi Did you ever work this out? I am looking for the same thing as you and struggling to find any examples.

**Comment by rasmus** [comment]
@mattgi There isn't any complete guide for that specific setup. You'll have to piece together the configuration from the documentation and as there's not (yet) any support for .NET Core IoC, you'll have to use e.g. Autofac. But as Microsoft recommends changing the IoC container away from the default, you might as well choose Autofac.

For the rest is basically a lot of calls to extension methods on `EventFlowOptions.New`. You could have a look at the shipping example, specifically the [integration test](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.Examples.Shipping.Tests/IntegrationTests/Scenarios.cs). The shipping example has a core domain project and then read models in another project.

**Comment by rasmus** [comment]
From [Microsoft docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1)
> The default services container provided by ASP.NET Core provides a minimal feature set and isn't intended to replace other containers
i.e., you should use another container solution

**Comment by ppumkin** [comment]
@rasmus that document was last updated 2016 ... netcore has been to everest and back since then, twice.
I have actually used the example that is in source for aspnetcore and that seems to work.

This is first time in netcore i had to use another container other than the shipped one.. and we have tons of services in production working just fine. I get it... this project was started way before all this happened.

End of day the aspnetcore example works without changing anything else on the constructors.. so i don't care as long as it works. 

Probably need to update the docs somewhere with this example??

**Comment by mattgi** [comment]
I did get things all working - had to fork a few things like the eventstore library and rebuild it, targeting core instead of standard, but for the mostpart it was easy enough once I remembered how to 'dot net'.

In the end we moved to TypeScript/Node due to the ease of dealing with JSON. We also use a lot of redux-like stuff in the client so a single event sourced solution in TypeScript worked best for us. EventFlow was/is a great learning resource though!

**Comment by rasmus** [comment]
@mattgi good to hear. If you have any specific problems, please create issues either here or in the documentation repo. While I might not always have the time to do everything, its still good to know whats lacking.

As for the .NET Core support for EventStore, there's a PR for that #468

**Comment by AurelianTimu** [comment]
It would be really good if a .net core web api example would be available.

**Comment by johnny-chan** [comment]
@AurelianTimu - yeah i totally agree with you so i have just created this very [simple solution](https://github.com/johnny-chan/EventFlowDemo) that uses the command/event types from the "GettingStarted" . It is a web api running .net core 2.2.

**Comment by rasmus** [comment]
@johnny-chan If you are interested, you can add a link to your example from the read-me under the section [external examples](https://github.com/eventflow/EventFlow#external-examples).

**Comment by johnny-chan** [comment]
@rasmus - ok, i will do that, i have cloned the project, created a separate branch but i am unable to push the branch to remote.  Please suggest how best to add my example.
