### ISSUE TITLE
Did eventflow support Simple Injector ?

### ISSUE THREAD

**Issue by minhhungit** [eventflow/EventFlow#274]
Hello team
I heard that [simpleinjector](https://simpleinjector.org) is the fastest dependency injector for .NET
Right now we just support Autofac, right ? Can we consider simple injector

**Comment by rasmus** [comment]
I'm relocating to a new house this week and have only limited internet and computer access.

Usually the applications I have worked with it isn't the time spent by the IoC that's the limiting factor, especially for applications that implement DDD. So while simple injector might be faster, the time saved also needs to be compared with the features provided, release frequency, stability and ease of use.

I'll have a look at simple injector when I'm settled in the new house. Until then anyone is free to submit a PR.

**Comment by hvidgaard** [comment]
Regardless of speed, SimpleInjector is my prefered DI container for new projects. It is however hard to integrate it properly due to the opinionated nature of it. After deciphering EventFlow structure and sources for a day and beginning to understand basic parts of it, I'm willing to give it a shot. But what is the intended extensibility point for a new DI container? Is it `IServiceRegistration `and the `Resolver` interfaces?

**Comment by rasmus** [comment]
@hvidgaard if you're working with .NET Core you would wait a bit and use the support for `Microsoft.Extensions.DependencyInjection`. Does SimpleInjector support that? If so, you wouldn't have to do anything

**Comment by rasmus** [comment]
For examples on how to do an implementation, see the [built-in](https://github.com/eventflow/EventFlow/tree/develop/Source/EventFlow/Core/IoC) (for test only) or have a look at the Autofac implementation (might be the easiest).

EventFlow provides a test suite named `TestSuiteForServiceRegistration` that you can use to verify an implementation, its part of the `EventFlow.TestHelpers` NuGet package

**Comment by hvidgaard** [comment]
@rasmus It certainly is fairly simple to integrate with the `Microsoft.Extensions.DependencyInjection` interface. Maybe I'll wait for that, but it is a case of comforming container. I've tried to implement `IServiceRegistration` and the `Resolver` interfaces and run the tests from the Autofac test project. However, especially the `IServiceRegistration` is written to fit Autofac (and with good reason since it is what you use).  I have the following issues:

- SimpleInjector cannot register multiple types for the same service type in the way `keepDefault` does. In fact if you want to register a collection of implementations for a type, you must use a special API.
- SimpleInjector has buildin support for decorators, it just needs the types. I cannot extract that from the `Func<IResolverContext, TService, TService>` (might be a case of me not knowing enough about reflection).

So to escape the IServiceRegistration and utilize some of the strengths of SimpleInjector it seems that I have to implement `IEventFlowOptions`?
