### ISSUE TITLE
Consider making committing events sync instead of async

### ISSUE THREAD

**Issue by withinboredom** [eventflow/EventFlow#412]
By making commits async, they can get queued up in the thread pool and cause many optimistic concurrency exceptions, causing throughput to drop. If commits were synchronous the engineer can decide if an event can be performed async (by wrapping it in a `Task`). 

I discovered this by writing up a simple benchmark that published 20k commands in a short period of time to a pool of random aggregates.

Example:
``` c#
            var start = DateTime.Now;
            for( var i = 0; i < iterations * ids.Count; i++ )
            {
                var pubStart = DateTime.Now;
                var commands = new List<Task>();
                new Action<int>(imp =>
                {
                    var t = Task.Run(() =>
                    {
                        var wait = commandBus.PublishAsync(
                            new IncrementCommand(ids[rand.Next(ids.Count - 1)], dispatched++), CancellationToken.None);
                        waiter.Add(wait);
                    });
                    commands.Add(t);
                })(i);
                pubTime.Add( DateTime.Now - pubStart );
                var execStart = DateTime.Now;
                await Task.WhenAny( commands );
                execTime.Add( DateTime.Now - execStart );
            }
            Console.WriteLine( "Waiting on the last of the commands" );
            var end = DateTime.Now;
            await Task.WhenAll( waiter );
```

**Comment by rasmus** [comment]
Sorry, EventFlow won't go sync on command publishing (or any other part that's currently async) as its one of its "key selling points".

- Optimistic concurrency exceptions only happens when multiple threads tries to commit events to the same aggregate ID
- EventFlow doesn't use any `Task.Run(() => ...)`, mainly to be web friendly, but also let any explicit thread usage be up to users of EventFlow. Yes, you still get IO-completion threads, but that's the nature of async/await. I would recommend that you don't use `Task.Run(() => ...)` for anything but some CPU-only intensive task, i.e., something that hasn't any IO

If you haven't read the articles Stephen Cleary has written about async/await, I can highly recommend it, especially these two

- https://msdn.microsoft.com/en-us/magazine/gg598924.aspx
- https://msdn.microsoft.com/en-us/magazine/dn802603.aspx
