### ISSUE TITLE
ASP.NET Classic integration: commands and metadata providers execute on thread that doesn't have HttpContext available

### ISSUE THREAD

**Issue by bedej** [eventflow/EventFlow#551]
Title says it all, but I'm not sure if this is really a bug in so much as a deliberate design choice. Can anyone shed some light here?

Scenario:
I'm trying to implement an ASP.NET version of the AspNetCore integration that captures API controller request information (in my case it's the user Id information, a custom class IUserInformation, which I have injected in Autofac with scope InstancePerRequest(), populated by a base class of all my API controllers.

Attempts:
- First attempt: implement an IMetadataProvider, and attempt to resolve my IUserInformation object dynamically in the ProviderMetadata method. Result: Autofac exception because HttpContext is not available. I look at the thread, and sure enough this is running in a background thread, not the API controller thread.
- Second attempt: I created a base class for my aggregates, that derives from AggregateRoot and overrides Emit(), and attempted to dynamically resolve IUserInformation there, and add it to the metadata. Same result.

Question:
- Clearly this must work if you're using HttpContextAccessor in ASP.NET core, since that's what the AspNetCore integration uses?
- Is the decision to execute all the EF commands on a background thread with HttpContext propagation turned off a deliberate one? If so, was that deliberate? 
- Is there any recommended way around this, without having to stick the IUserInformation into every single command body at command creation time in my API Controllers, or the big hammer of switching to ASP.NET core (planned, but I can't do it right now)? Is there a class I can change to get the commands to execute in the original controller thread or at least have the background thread have HttpContext populated?

Thanks for anyone help/information!

**Comment by rasmus** [comment]
Its properly due to the fact that for every `await` in EventFlow, there's a `.ConfigureAwait(false)`. This tells the .NET that it doesn't need to return the operation back to the same context, e.g. when a blocking IO operation completes, it doesn't restore the synchronisation context (as far as I remember).

Here's a good article about the sync context https://msdn.microsoft.com/en-us/magazine/gg598924.aspx

As a side note, you should almost on only rely on articles on MSDN and specifically from Stephen Cleary when it comes to anything about async/await. I have read quite a lot of Stackoverflow answers and articles that contain wrong information.

On a more general level, I can recommend this video on Channel 9 https://channel9.msdn.com/Events/TechDays/Techdays-2014-the-Netherlands/Async-programming-deep-dive by Bart De Smet (he's one of the developers that made us write `.ConfigureAwait(false)`)

**Comment by rasmus** [comment]
In short, you need to make the HttpContext available by some other means than `HttpContext.Current`, e.g. pull it from OWIN, use some Autofac magic or manually put it in a `AsyncLocal<>`. Please note that these are just ideas from the top of my head. I have never had the use in any of our projects.

**Comment by bedej** [comment]
Thanks @rasmus - AsyncLocal was the thing I needed and didn't know about. It's a bit ugly obviously, but it'll keep us going until we can migrate to ASP.NET Core. I'll leave this open but you can feel free to close it - not sure what your policy is.

Also, it's a small world. I used to work at Microsoft and I actually know Bart from way back.

**Comment by rasmus** [comment]
@bedej small world indeed, if you ever see him again, tell him my fingers are hurting for all the extra typing 😄
