### ISSUE TITLE
Aggregates/Entities - Many To Many

### ISSUE THREAD

**Issue by kokhans** [eventflow/EventFlow#563]
Hello,
How to design aggregates/entities/read models with many to many relationships.
Could you provide some example?
Thanks!

**Comment by malclear** [comment]
Hello, 
Your question is an important one, I think (because I had it too!), and this is what I have found: with regards to many-to-many relationships, don't do it! Think instead about what your aggregate boundaries really should be. Find that entity which is truly more dependant on the other to be the aggregate root which contains the traversible collection. The other entity should instead rely on a service query for its collection of related entities.
Udi Dahan explains it better: http://udidahan.com/2009/01/24/ddd-many-to-many-object-relational-mapping/

**Comment by rasmus** [comment]
@malclear thanks for that reference!

**Comment by rasmus** [comment]
Closing this as answered

**Comment by rasmus** [comment]
Darn, the link seems dead
