### ISSUE TITLE
How should to take the advantage of aggregate state

### ISSUE THREAD

**Issue by PhatHoang21** [eventflow/EventFlow#568]
I'm confused about using aggregate State. Could you guys talk me through when should I use it, how can I use it correctly. Its data will be saved to event store when a event is fired, isn't it?

I have a use case. I need to manage user and all devices belong to each user, every users can share their device with others. I'm also building a materialized view that show all users with all devices they owned or were shared. 

What am I doing is when adding a new device to an user, saga will handle DeviceAddedEvent, update device's info. Then I query all devices related to given user from read model and it sends a command named UpdateDevicesCommand to User aggregate. 

The question is should I do a query to get related devices and update whole data in aggregate state? Or just send the new one and let State add it to existing collection?

Many thanks.

**Comment by wgtmpeters** [comment]
The state in the aggregateRoot will be rebuild for each command the aggregate is processing. So It should contain all the users devices when processing the new AddDeviceCommand. In which case your apply on the aggregate should add it to the collection in the state of the aggregate.
I do wonder why you need a Saga in this case. 
Where is the DeviceAddedEvent coming from? As a result from a command that is send to a user aggregateroot?

**Comment by wgtmpeters** [comment]
Ok so the Saga already has some state in it to determine to which user the UpdateDevicesCommand should go ? 
Anyways you should only send the new device with the command ,previous onces should already be in the aggregateState by applying previous DomainEvents that resulted from previous UpdateDevicesCommands to the user Aggregate.

I guess you would not even need a query then, because I expected you already have all the information you need to create the Command for the user from the DeviceAddedEvent.

**Comment by rasmus** [comment]
Closing this as answered
