### ISSUE TITLE
Saga and error handling

### ISSUE THREAD

**Issue by mbican** [eventflow/EventFlow#606]
I find error handling in saga's lacking. So far I don't have the whole picture but I am starting to see a way.
I see it that ideally saga should be a simple state machine. Receive one event, produce one event (to move internal state of the state machine) and publish one command. Then the command either succeeds or fails. Those are two possible transitions of the internal state of the state machine after the command is finished.

The original definition of saga was that there is a list of pairs of forward command and compensation command (which can reverse the forward command in case of an error). So I see it that if one command fails then compensation commands for all previous commands should be published in reversed order starting with the failed command and going all the way back to reverse the very first command. (note: I don't mean to publish all compensation commands at once but one by one throught the usual transitions of an internal state machine)

One hour later,
We should introduce:
`CommandFailedEvent<TCommand> `
event that will be delivered to a saga automatically by the system in case of a failed command previously published from the saga. Seems easy and straight forward :-)

**Comment by rasmus** [comment]
Agree, the saga error handling is indeed lacking and communicating any failed commands back to the saga itself makes it easier to see the entire flow.

Disregarding the interfaces that EventFlow uses for sagas, EventFlow does support changing the underlying saga implementation, do a degree. There's even a [test for it](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.Tests/IntegrationTests/Sagas/AlternativeSagaStoreTests.cs).

However, as this issue is on how EventFlow interacts with sagas, it still makes sense to have better out-of-the-box error handling.

**Comment by rasmus** [comment]
Now possible `ISagaUpdateResilienceStrategy`
