### ISSUE TITLE
Automatically add saga id to event metadata + create default SagaLocator

### ISSUE THREAD

**Issue by mbican** [eventflow/EventFlow#608]
In documentation about sagas there is this thing about storing saga-id into event metadata. It looks intuitive but it doesn't work out of the box :-(. I would like to make it work. Here is how:
1) from PublishAsync pass sagaId and saga type name into ICommandBus.PublishAsync()
2) overload ICommandBus.PublishAsync() so it takes an extra argument eventMetadata
3) pass event metadata to IAggregateStore.UpdateAsync()
4) pass event metadata to AggregateRoot.CommitAsync()
5) actually add eventMetadata into _uncommittedEvents
6) then we could create a default implementation of SagaLocator which would find saga id and type name in event metadata

or the second option could be to put eventMetadata into command along with already included ISourceId

**Comment by ProH4Ck** [comment]
Hi,
I think this could be very uesful.
Following steps posted by @mbican I started to code an implementation here: https://github.com/ProH4Ck/EventFlow/tree/feature/saga-metadata
At the moment It's a full WIP and it works only for commands published by the saga.
What do you think?

**Comment by Brandon2255p** [comment]
I am also busy implementing this. We need it for tracing back to find where an event originated. 

Since we use RabbitMQ to send our commands, we do not have access to the HttpContext. I have built a working CommandMetadataContext which is basically like the HttpContext but it allows us to read the metadata from the RabbitMQ message and insert it into the IoC for that async call. 

That eliminates the `aggregate.SetCommandContext(command);` in Source/EventFlow/Commands/CommandHandler.cs

And the metadata falls in line with the normal IMetadataProvider implementation that is already available

thanks @ProH4Ck for adding the metadata to commands - that is very useful and was going to be the next step
