### ISSUE TITLE
Optimistic conccurency

### ISSUE THREAD

**Issue by poumup** [eventflow/EventFlow#655]
**Context:**

I have several instance of a microservice based on eventflow.

When the `SaleAggregate` emit the event `SaleCreated`, then 2 subscriber of `SaleAggregate` fired.
Both emit new event each other.

**Problem:**

When subscribers commands were fired the eventflow get the same **`Version`** for both event and try to commit those events in the database.

I think the problem is not related only to postgres.

**So:**

`OptimisticConcurrencyException` was throw, i think it's due to this line.
because the property **`Version`** is not distributed. May be base the SQL provider on a sequence ?

https://github.com/eventflow/EventFlow/blob/ae1bfb064286cb1f8981c7f3f127ec3d2a4f8e3f/Source/EventFlow/Aggregates/AggregateRoot.cs#L83

all comments are tips, or ideas are welcome.

**Comment by poumup** [comment]
@rasmus did you agree that this issue can be occurred with scaled services ?

**Comment by rasmus** [comment]
@poumup I might have misread your issue when first created. The events are given but the `AggregateRoot` code, but its the event store, e.g. MSSQL, that ensures that no to events are written with the same version. If it does happen, a `OptimisticConcurrencyException` is thrown and the command is retired, a number of times even (https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/Configuration/IEventFlowConfiguration.cs#L47).

This is expected behavior as EventFlow uses optimistic concurrency by e.g. creating a unique key based on the aggregate ID and the event version.  

Here's the integration test that verifies that the exception is correctly thrown.
https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.TestHelpers/Suites/TestSuiteForEventStore.cs#L278

**Comment by rasmus** [comment]
This hasn't surfaced since and it lacks information. Please open again if there's still a problem
