### ISSUE TITLE
Subscriber from different application

### ISSUE THREAD

**Issue by smithderekm** [eventflow/EventFlow#673]
This question is based on a big assumption, but I thought I would still ask to get some insight.

I have two .net Core applications: an API and an MVC app.  The API is where my primary EventFlow configuration exists, using MsSql as the event store.  All this works great, and my events are written to Sql and Read Models are getting updated.  In this bounded context, there are no subscribers to the events that are emitted.

I now want my MVC app, which represents a different bounded context, to subscribe to these events and affect data in its own datastore.  

I **assumed** that I could have a matching EventFlow registration in the MVC app and just register the Subscriber, and in doing so it would 'monitor' the Events directly from MsSql.  But my 'remote' event subscriber is never called and in the console of my API application I will see a message to the effect of 'Did not find any subscribers to event 'EventName'.

I looked at the sample code tied to https://github.com/eventflow/EventFlow/issues/615 (Vehicle tracking) and it appears that in addition to the subscriber code, there was also a Service registered to be the listener (in that case to RabbitMq).  I also reviewed https://github.com/eventflow/EventFlow/issues/362 and it indicates that they got remote subscribers working, but perhaps not on MsSql.

So, I guess my questions are:
1. Can the MsSql event store be 'shared' between two applications in a pub/sub manner?  If so, how should the registration of the subscriber occur?  Do I need a 'listener' in addition to the Subscriber itself?

2. Is anything additional required to set up a subscriber from a 'remote' domain?  Does it have to be registered in the 'primary' domain in order to get notified?  I'm obviously trying to keep these isolated from one another.

I have largely committed to EventFlow for this project and appreciate all the work put in to it.

**Comment by rasmus** [comment]
Good question, I'll try to get back to you this evening (GMT)

**Comment by rasmus** [comment]
Its a great question and you have two options.

- Use `ISubscribeAsynchronousTo<>` instead of `ISubscribeSynchronousTo<>` and then use the `EventFlow.Hangfire` NuGet package to set up the handling of subscribers. Be sure to read the [section in the docs](https://docs.geteventflow.net/Subscribers.html#asynchronous-subscribers) on asynchronous subscribers. You need to ensure that everything serializes properly, maybe even make the [JSON pretty](https://docs.geteventflow.net/ValueObjects.html#making-pretty-and-clean-json) in order to make it easier to upgrade or use different types at a later point.

- Only have your domain code in one of the services and expose an API that the other calls. The API shared between the services wont contain methods to do direct actions on the domain, but provide some higher level of abstraction that makes sense in your domain.

Which one you choose depends a lot on taste and these size of your services. We went with the latter in one of our services at work and it made sense for us. We even went as far as separating the two into two "deplorables" that have their own release cycle. In our cases it allowed us to create loose coupled domains.

**Comment by smithderekm** [comment]
Thanks for the prompt reply.  I'll start down the HangFire route and report back.

**Comment by smithderekm** [comment]
@rasmus - I literally could not connect the dots mentally to sort out the Hangfire approach (which I may revisit, but I had a time constraint), so I ended up proceeding to implement RabbitMQ event publishing, and created queue watcher and subscriber based on @MongkonEiadon example.  So far the event flow appears to be good.

However, apart from marking the queue watcher to auto-acknowledge the messages, do you have a recommendation for ensuring that events only get processed a single time by the assigned subscriber(s)?

Thanks in advance, and if you'd prefer I spawn a new thread for this follow up question I'm happy to.

Derek

**Comment by rasmus** [comment]
@smithderekm if the resulting event is used within another context and that context is implemented using EventFlow, you could have a look at this.

https://docs.geteventflow.net/Commands.html#ensure-idempotency

**Comment by rasmus** [comment]
Closing this as a stale question
