### ISSUE TITLE
Does the default ReadModelPopulator also invoke event subscribers?

### ISSUE THREAD

**Issue by trancefreak77** [eventflow/EventFlow#717]
In our current implementation we sometimes have event subscribers on the read side instead of a read model. (Example: Register user where the username column has a unique key).

The subscriber does the insert and catches the unique key violation exception and publishes a compensation command.

When the events are replayed, do the subscribers also get invoked? This would result in a re-publish of a command which in turn will result in creating a new event while replaying.

If the subscribers do not get invoked, the read side will miss content if tables are updated by subscribers instead of simple read models because not every scenario can be handled by the current read model implementation.

How does eventflow handle this scenario?

Kind Regards,
Christian

**Comment by ckoehler-pillar** [comment]
Hey Christian,  Using readmodels, and things outside of the aggregates to validate models can get tricky as you noticed. At the surface I would suggest creating your own custom id for users that way you can easily check at the top of a command handler if the aggregate loaded is new. This should help quite a bit.

**Comment by trancefreak77** [comment]
Hi ckoehler,
Thanks for your input. On the write side we cannot do username uniqueness checks because we can only fetch user aggregates by id. So according to some blogs and cqrs + event sourcing best practices we create a new user and use the insert at the read side to check if the insert succeeds or not. In case it does not a compensation command is triggered.

As far as I saw in the EventFlow Code, subscribers do not get invoked when replaying events, so re-triggering a command is not an issue.

But there is still the problem with subscribers which insert data into n:m mapping tables because eventflow by default does not support them. Only 1:n is supported by read model locators. Additionally there also should be the possibility to subscribe to some event and when it is triggered a subscriber can do some db lookups and fill up data from different tables into an aggregated one.

With the current eventFlow implementation there will be data loss on the read side while replaying events because subscribers are not taken into account.

@rasmus: Do you have any idea or concept how this could work? Maybe taking subscribers also into account and disabling the commandBus while replay is executed and when replaying events is finished, the commandBus gets purged or any other idea.

Kind Regards,
Christian

**Comment by ckoehler-pillar** [comment]
Sorry perhaps I wasn't very explicit, Your ID should be the uniqueness constraint. In eventflow you can implement your own IIdentity that is the username and that will the do the uniqueness check for you. and you can always guard by doing aggregate.new in command handler to ensure you are not doing creates against an aggergate that is already existing. I am not sure what blogs, cqrs + event sourcing best practices you are referring to. Compensation commands typically arent used during creation of new aggregates because you can enforce uniqueness easily. Hope that clears that portion of it up. 

As for wanting subscribers to be triggered on a replay of events...the replay of events is suppose to just be for rehydration or restoration...It is not a new trigger of actions being entered into the system but past actions of the system...i.e the subscriber already ran when the initial action was taken.  I could be wrong but it sounds like you are trying to form a 3NF relational model from events on rehydration and are wanting to bring in events from many outside bounded context from the aggregate. This isn't how event sourcing works. You rehydrate the aggregate with the events that have been applied to that aggregate and only that aggregate. You do not look up other aggregates to get their current state and shove that into the original aggregate. If you catch my drift.

On the data loss side of subscribers this is solved by implementing Hangfire. There is a section on it in the docs that can help you.

**Comment by trancefreak77** [comment]
This is an interesting idea to implement my own IIdentity which is the username. This will work very well if the system does not allow the user to change his username. Otherwise all aggregates referencing the userId need to be updated with a new Id.

But it is still unclear to me how to handle situations where a readModel is not sufficient. Let's stick to the easy user <=> group assigment as an example.
An administrator can create users and he can create groups. Additionally he can assign a group to a user. This action emits a GroupAssignedToUser event. The read side has a mapping table userGroup with PK userId and PK groupId.
This is needed because the UI needs to display all groups a user belongs to and in the group view the UI displays all users belonging to that group.

As far as I know, eventFlow does not support readModels with more than one PK. For this we need a subscriber which listens to this event and does an insert into the userGroup table for the given user and group Ids which are stored in the event.

A readModelLocator can't be used because it is an n:m relation.

When replaying the events (I know that replaying must not create new events nor commands) the user and group tables are populated by their readModels but the mapping table will be empty because subscribers are not taken into account by the current ReadModelPopulator implementation.

Therefore I am not sure how to handle this with eventFlow.

@rasmus: Do you have any ideas how we could handle that?

**Comment by ckoehler-pillar** [comment]
You should read https://martinfowler.com/eaaDev/EventSourcing.html and keep in mind what you are trying to do. To me you are describing that you have internal code (subscribers) that are making data outside of the aggregates in a read model "map" table. This doesn't make sense. The whole purpose of event sourcing is to keep everything in the events for replay-ability, tracking, historical, etc. To keep with your user to group assignment...if each one is an aggregate that may be a bounded context line between the two in your application. If groups are an aggregate and you want to assign an existing user to an existing group, you would have an event and that event is stored and then your user read model for the user can listen to that event and update itself. You don't need a mapping table between the user read model and group read model because once the information is stored once why duplicate it? If your plan is to hydrate a group with all users then have the group read model listen to users assigned to group events and put all the data into the read model at that time.

**Comment by trancefreak77** [comment]
Maybe I should have pointed out that we use EntityFramework Core with a MSSQL DB on the read side. Given our user read model looks as follows:
`
public class User : IReadModel, 
                              IAmReadModelFor<UserAggregate, UserId, UserCreatedEvent>,
                              IAmReadModelFor<UserAggregate, UserId, GroupAssignedToUserEvent>
{
  [Key]
  public string Id { get; set; }
  public string Username { get; set; }
  public virtual ICollection<GroupReadModel> Groups { get; set; }

  public void Apply(IReadModelContext context, IDomainEvent<UserAggregate, UserId, GroupAssignedToUserEvent> domainEvent)
    {
      Groups.Add(new GroupReadModel(....));
    }
}
`
What Entity Framework Core does is to add a column UserId to the Group table in the background. So it is a 1:n relation which means the same group can only be assigned to one user and one user can have n groups.
If another user gets a group assigned which is already assigned to another user the userId for that record will be overwritten with the new userId and this group is no longer part of the other user.

So normally with relational SQL databases, for an n:m scenario, one needs a mapping table with two primary keys.

This has nothing to do with domain logic, aggregate boundaries or anything else you mentioned.

Or am I completely wrong? Do you have a solution how this can be modeled on DB side so that we do not need a mapping table? I and my collegues don't have a solution.

I would be really happy if you could help me and we could get rid of using subscribers for such scenarios.

**Comment by ckoehler-pillar** [comment]
Do you have group to users read model with event? I think if you add that and add it into the ef core context it should built it itself. This sounds more like an EF problem not an Eventflow problem

**Comment by trancefreak77** [comment]
Yes, we have a UserGroupReadModel which could listen to the GroupAssignedToUser event but the problem is that EventFlow does not support read models with two primary keys. EventFlow throws an exception. That is the reason why we started to use subscribers for this because there I have not found any other solution.

**Comment by trancefreak77** [comment]
@rasmus Do you have a solution for the issue that a read model can only have one primary key or maybe you have a better idea how to handle m:n EF core relation tables?

**Comment by 7thcubic** [comment]
Technically you could extend and overwrite
https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.EntityFramework/ReadStores/EntityFrameworkReadModelStore.cs

**Comment by rasmus** [comment]
@trancefreak77 sorry for getting back late, I have been on an extended Christmas vacation and trying not to do too much work related.

EventFlow provides two different layers for you to hook into the read model pipeline and their interfaces are relatively simple

1) If your needs aren't too far from the current implementation, you could implement another `IReadModelStore<>` and register it similar to that of any other store. Have a look at the `InMemoryReadStore` which is by far the simpler implementation.
1) If you need something more custom, you could implement `IReadStoreManager` which gives you total freedom.

Both solutions tie into the read model population.

I have tried out a few implementation for m:n, but couldn't figure out how to make anything generic that would fit into the framework 😢

**Comment by frankebersoll** [comment]
It appears that your question has been answered. Since we haven't heard anything about it for a while, we hope that your problem is solved - if not, please reopen the issue. Thanks!
