### ISSUE TITLE
Version Number inconsistencies - Who owns the version number?

### ISSUE THREAD

**Issue by dvanherten** [eventflow/EventFlow#729]
Event Flow aggregates appear track their own Version through incrementing the version as it processes events. I'm not well versed enough (yet) to understand when and where the version is used within the context of Event Flow code. I have seen that we do appear to translate it to the Aggregate Sequence Number in events and that number is used for checking against stream expected versions in the Event Store connector.

Take this scenario
1. Aggregate running for a while (has events)
2. An event gets scavenged for some reason (perhaps there is an assumption that this never happens)
3. The aggregate will never update again because the expected version passed to the aggregate stream will always be off by one.

The root of my question: Is there a reason for why we don't track and respect the number provided by the persistent store such that we can provide it back as the proper expected version? I can see wanting to have a version that represents the events actually used, but I feel we need to make sure we also provide a store with the same expected version as it gave us initially.

**Comment by dvanherten** [comment]
Not entirely sure, but #564 seems related.

**Comment by mbican** [comment]
Hi,
can you please iterate more on the 2) "event gets scavanged" ?

basically the idea is, events are the single source of truth so the version of the last event in given aggregate is the version number of that aggregate. Second there can't be any gaps in event numbers for given aggregate once the event is committed it can't get lost at least not in the event store.

If we consider read models or sagas or other event subscribers then the current event flow implementation is weak see #439 because it can happen that event committed to event store is not delivered to read model or saga or event subscriber so read model can receive a gap in version numbers. Is your question related to read models?

To answer your last question, we don't persist aggregates we persist just events, therefore version is stored in events it cannot be stored anywhere else because that would break the "Event Sourcing" paradigm

**Comment by mbican** [comment]
or is it that you just assume that there is already a gap in events just as a theoretical case and we are now talking about how should aggregate deal with such situation? (e.g. to crash and report that there is missing event)

**Comment by dvanherten** [comment]
Sorry Scavenged was probably a poor word choice. I'll update to delete. Basically, in EventStore, if a stream is deleted for any reason and then reused, the event numbers will continue from where they left off. I agree in most cases you'd never want to delete a stream or any events, but lets pretend for a second that it can happen. For instance in #564, it points out that identities aren't guaranteed in SQL and I can't speak to whether every store will actually guarantee no gaps in their event numbering.

So here's an example that could happen. (admittedly it happened to me in a dev environment)
 - User Aggregate where the id was deterministic id based on the email. (handy for us, but perhaps we could avoid)
 - Lets say the stream for a user has 4 events (event numbers from 0-3)
 - GDPR right to delete request is made.
 - We delete the stream (and all the other downstream bits to remove them completely from our system)
 - Later on that user comes back and because of determinism the stream is recreated with the same Id (assuming 4 events again they would be event numbers 4-7)

From an event store perspective this is fine. The stream only consists of the events relative to the new data provided and the stream is in order and all that goodness. The only awkward bit is that the event stream doesn't start at 0.

Event Flow however builds it's own version based on the number of events processed and uses that for the expected version in the store (instead of what the last event provided as its number). So when it tries to update it will fail because of expected version not being what event store expects. The initial write of events will work the second time around because the stream doesn't exist and thus there is no expectation of which event to be on.

In a perfect world, no gaps will ever exist, but I was caught off guard when I learned that Event Flow enforces that assumption on the stores.

**Comment by dvanherten** [comment]
In a nutshell I'm suggesting that something along the lines _(for example only, this would be more involved than this and has side effects I'm not considering, but for clarity to the issue)_
 
https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/Aggregates/AggregateRoot.cs#L194

Could be taken out of that method and moved to between lines 156 & 157 as:

`Version = domainEvent.AggregateSequenceNumber;`

Now the max sequence number when going to save would be what the stream expects to avoid false positives of optimistic concurrency exceptions.

**Comment by mbican** [comment]
Oh, I see so to summarize:

1) we are talking about conflict of deleting aggregate with all its events and than recreating it with the same id
2) the database that persists events in your case is EventStore by Greg Young

so it could either be that 2) there is a bug in the IEventPersistance adapter for EventStore and/or 1) the EventFlow doesn't consider use of deleting aggregate and recreating one with the same id

**Comment by rasmus** [comment]
Just a short introduction on how EventFlow handles event versioning. EventFlow uses optimistic concurrency checking, which basically means that multiple threads generating events simultaneously, will have the same version numbers. However, these events only live in memory and aren't considered as "happend yet" as they haven't been persisted to the event store. The underlying event store is then responsible for detecting if there's a conflict. The basic example is the MSSQL event store which has a unique key constraint on (aggregate id, event version), which means that a [`OptimisticConcurrencyException`](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.MsSql/EventStores/MsSqlEventPersistence.cs#L152) will be thrown for all but one of the threads. Each of these threads will then reload the aggregate stream and then retry the command on the reloaded aggregate. All this happens automatically. When events have been successfully been committed to the event store, they are published to read models and subscribers.

EventFlow doesn't support re-use of aggregate IDs, which I personally can get my head around why would make sense. If you give an aggregate an ID, that's its ID forever. If new events are generated on the same ID at a later point, I would expect the event stream to continue from where it was previously.

In our systems aggregates are given IDs based on GUID's, which means we never re-use them. We do delete whole aggregate streams in order to save storage space on our database servers, but the event streams are still present (without any GDPR related information) in our Hadoop cluster. Thus reusing an ID for something else would corrupt our data integrity.

Out of curiosity, why do you need to re-use aggregate IDs?

**Comment by dvanherten** [comment]
> Thus reusing an ID for something else would corrupt our data integrity.
> 
> Out of curiosity, why do you need to re-use aggregate IDs?

We took advantage of the Deterministic guids off of an email to save having to do a lookup by email to get the aggregate id. This has the side effect that a stream could theoretically be reused if a user requested removal and then that user used our system again at a later date. We can shift to a lookup and a non-deterministic guid to work around this.

Admittedly, this came up because we were doing some development with an area of our app that was still somewhat hardcoded so the guid didn't change even though we killed a stream. The user sample is a way it would have happened if we continued down our planned path which no longer is an option.

I can see how that versioning strategy would work well with the MSSQL side because you have full control over the event number generation and can make sure you never have a gap. EventFlow essentially manages it from end to end. 

As EventFlow doesn't control the event number provided by EventStore, I'm double checking with some EventStore folks to find out if they guarantee no gaps as that would also cause this problem (not just stream deletion) and my worry is that an aggregate stops being writable because a gap occurs by the system for some reason and it ends up being impossible to mend outside of migrating events into another stream (and hoping again for no gap). 

I very well might be making a mountain out of a molehill here, but want to make sure my bases are covered.

**Comment by rasmus** [comment]
@dvanherten understandable and thanks for the in-depth description. I also used the email for a deterministic guid for an internal training session, it is very convenient 😄

**Comment by mbican** [comment]
seems like it can be solved  IEventPersistence.CommitEventsAsync() method returns events after committing them. In method EventStoreEventPersistence.CommitEventsAsync() if it detects conflict and the first input event starts with sequence number 1 and there are no events in the stream, it could just increase the events sequence numbers and try again, and then the aggregate would have to correctly read the version number from the events as suggested by @dvanherten . But then the gap in sequence numbers could break anything else that counts on there being no gaps in event sequence numbers so it is probably not a good way to go, and the event ids would break :-( .

Let's call it a feature that you cannot write events to an aggregate that has been previously deleted. Maybe it should be in all IEventPersistence implementations that after aggregate deletion there is some sort of a tombstone to make sure it will not be writeable again

**Comment by dvanherten** [comment]
Fair enough. For me the event number coming from the Event Store would be part of the source of truth so it does feel funny to me that we change it by incrementing a Version internally and using that for future writes as the expected version. (if we didn't, this wouldn't be an issue)

That said, I can understand that deleting streams and reusing them is probably not a great idea so it's probably fine to not worry about this. 

In other news, I did ask in an Event Store channel whether no gaps is guaranteed and it sounds like it is so we should be fine from the gap side of things.

@rasmus We can probably close this issue I think.

**Comment by bartelink** [comment]
FWIW, in [Equinox](https://github.com/jet/equinox), we intentionally don't expose a version in the API, except in the lower level storage driver, partially to handle cases where some events at the start of the stream are either deleted (in EventStore), or not loaded (if you're reading events backwards until you hit a "known state" Reset Event).

This allows one to e.g. filter some events one wishes to expose in the programming model to a given subset.

At the point where you're attempting to append a set of events, the request is then matched with the source information (highest observed event index within the stream), and the write's `expectedVersion` is derived based on the low level data.

This proved especially relevant for the Equinox.Cosmos driver - in that case, an update can be made contingent on the `_etag` for a document not having changed (which lets you do OCC on document changes) - such an approach would also be pertinent for other document stores e.g. DynamoDB

**Comment by rasmus** [comment]
Sorry, forgot to close this
