### ISSUE TITLE
Issue about using Identity class

### ISSUE THREAD

**Issue by raminrahimzada** [eventflow/EventFlow#794]
Hi to all , firstly say that a great project 
So decided to migrate some of my projects into this
There is some strange situation about using Identity
For the simplicity I always use my identity classes named Id
But in eventflow using identity class as Id leads to some strange situations bcs when you remove the Id part of  [reference to code](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/Core/Identity.cs#L45)
```cs
 NameWithDash = nameReplace.Replace(typeof(T).Name, string.Empty).ToLowerInvariant() + "-";
```
then nothing remains from class name and Id becomes absolutely unusable with validation errors throwing even in Id.New
Is there already  a way to customize it ?
 For example maybe a virtual method like that
```cs
protected virtual string FirstPartOfIdentity()
{
    return new Regex("Id$").Replace(typeof(T).Name, string.Empty).ToLowerInvariant();
}
```
and for my situation i can override it in my own derived class as like that:
```cs
protected override string FirstPartOfIdentity()
{
    return "MyCustomIdFirstPart";
}
```

**Comment by rasmus** [comment]
@raminrahimzada thanks for submitting the issue. I'll have a look.

Since EventFlow uses the `IIdentity`, you can simply copy the `Identity<>` class (remember license header) to your own code base and do any modifications you like to it. You are not restricted to use the class provided by EventFlow. This is one of the core principles of EventFlow, interfaces everywhere and let developers replace the parts they don't like.
